FROM python:3.9.16

#sciagniecie repo
RUN git clone https://github.com/cogent3/cogent3.git

#pobranie zawartosci requirements.txt
WORKDIR "cogent3"
RUN pip install -r requirements.txt

#instalacja zgodnie z instrukcja z repo
RUN pip install "cogent3[dev]"
